# Generated by Django 3.1.7 on 2021-04-14 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('org_id', models.AutoField(primary_key=True, serialize=False)),
                ('org_name', models.CharField(max_length=50)),
                ('org_desc', models.CharField(max_length=200)),
            ],
        ),
    ]
