# Generated by Django 3.1.7 on 2021-04-17 03:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('c_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('c_name', models.CharField(max_length=20)),
                ('c_classroom', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('d_id', models.AutoField(primary_key=True, serialize=False)),
                ('d_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('t_id', models.AutoField(primary_key=True, serialize=False)),
                ('t_name', models.CharField(max_length=10)),
                ('t_dept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.department')),
            ],
        ),
        migrations.DeleteModel(
            name='Organization',
        ),
        migrations.AddField(
            model_name='course',
            name='c_dept',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.department'),
        ),
        migrations.AddField(
            model_name='course',
            name='c_teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.teacher'),
        ),
    ]
