# Generated by Django 3.1.7 on 2021-04-17 05:10

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('backend', '0002_auto_20210417_1107'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('p_id', models.AutoField(primary_key=True, serialize=False)),
                ('p_rate', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('p_comment', models.CharField(max_length=200)),
                ('p_cid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.course')),
                ('p_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
