# Generated by Django 3.1.7 on 2021-04-23 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'permissions': [('search_course', 'Can search course info on the website')]},
        ),
    ]
