# Generated by Django 3.1.7 on 2021-04-28 01:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('backend', '0005_auto_20210425_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='makecomment',
            name='m_commentid',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='backend.comment'),
        ),
        migrations.AlterField(
            model_name='makecomment',
            name='m_owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='BadComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('b_count', models.IntegerField()),
                ('b_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
